name: build
on:
  workflow_dispatch: # allows manual triggering
  push:
    branches: [$default-branch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-action@v1
      with:
        repository:  dawn-ico/dusk-dawn-notebook
        tags: main
