name: Build Notebook Container
on: 
  workflow_dispatch: # allows manual triggering
  push:
    branches: [$default_branch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@master

    - name: update jupyter dependencies with repo2docker
      uses: machine-learning-apps/repo2docker-action@master
      with:
        MYBINDERORG_CACHE: true
